### ISSUE TITLE
It would be perfect if we could add the lyrics page

### ISSUE THREAD

**Issue by yuexuan** [Shivamrai15/Spotify-Clone#2]
It would be perfect if we could add the lyrics page

**Comment by Shivamrai15** [comment]
I can add synced lyrics by just simply integrating with https://www.musixmatch.com. However, for this small project, I think paid APIs aren't necessary.  By the way, check out my new project, Safari, which is a very advanced music streaming platform https://github.com/Shivamrai15/Safari.
